# Generated by Django 5.2.10 on 2026-01-18 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Raison Sociale')),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('ACTIVE', 'Actif'), ('VIP', 'VIP'), ('LOST', 'Perdu')], default='PROSPECT', max_length=20)),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='Secteur')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('phone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom Machine')),
                ('type', models.CharField(choices=[('EXT', 'Extrudeuse'), ('IMP', 'Imprimeuse'), ('DEC', 'Découpeuse')], max_length=50)),
                ('status', models.CharField(choices=[('RUN', 'En Production'), ('STOP', 'Arrêt'), ('MAINT', 'Maintenance'), ('PANNE', 'En Panne')], default='STOP', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Désignation')),
                ('category', models.CharField(choices=[('FILM', 'Film/Papier'), ('INK', 'Encre'), ('GLUE', 'Colle'), ('SOLV', 'Solvant')], max_length=10)),
                ('quantity', models.FloatField(verbose_name='Stock Réel')),
                ('unit', models.CharField(default='kg', max_length=10, verbose_name='Unité')),
                ('min_threshold', models.FloatField(verbose_name='Stock Alerte (Min)')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix Unitaire')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fournisseur')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(max_length=100, verbose_name='Fonction')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Principal')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('CALL', 'Appel'), ('EMAIL', 'Email'), ('MEET', 'Rdv')], max_length=50)),
                ('summary', models.CharField(max_length=200, verbose_name='Résumé')),
                ('details', models.TextField(verbose_name='Détails')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('issue', models.CharField(max_length=200, verbose_name='Panne')),
                ('action_taken', models.TextField(verbose_name='Action Corrective')),
                ('downtime_minutes', models.IntegerField(default=0, verbose_name="Temps d'arrêt (min)")),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200, verbose_name='Tâche')),
                ('frequency_days', models.IntegerField(verbose_name='Fréquence (jours)')),
                ('last_done', models.DateField(verbose_name='Dernière fois')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('of_number', models.CharField(max_length=50, unique=True, verbose_name='N° OF')),
                ('quantity_planned', models.FloatField(verbose_name='Qté Prévue (kg/m)')),
                ('start_time', models.DateTimeField(verbose_name='Début Prévu')),
                ('end_time', models.DateTimeField(verbose_name='Fin Prévue')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifié'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminé'), ('LATE', 'En Retard')], default='PLANNED', max_length=20)),
                ('bat_file', models.FileField(blank=True, null=True, upload_to='bat/', verbose_name='BAT Validé')),
                ('produced_qty', models.FloatField(default=0, verbose_name='Qté Produite')),
                ('waste_qty', models.FloatField(default=0, verbose_name='Déchets (kg)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.machine')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.FloatField(verbose_name='Qté Consommée')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='core.productionorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyée'), ('RECEIVED', 'Reçue')], default='DRAFT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier'),
        ),
        migrations.CreateModel(
            name='TechnicalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_internal', models.CharField(max_length=50, unique=True, verbose_name='Ref Interne')),
                ('name', models.CharField(max_length=200, verbose_name='Désignation')),
                ('structure_type', models.CharField(choices=[('MONO', 'Mono'), ('DUPLEX', 'Duplex'), ('TRIPLEX', 'Triplex')], max_length=20)),
                ('width_mm', models.FloatField(verbose_name='Laize (mm)')),
                ('cut_length_mm', models.FloatField(default=0, verbose_name='Pas de coupe (mm)')),
                ('artwork_file', models.FileField(blank=True, upload_to='artwork/', verbose_name='Fichier Graphique (AI/PDF)')),
                ('artwork_version', models.IntegerField(default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.AddField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technicalproduct'),
        ),
        migrations.CreateModel(
            name='Tooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('CYL', 'Cylindre Hélio'), ('CLICHE', 'Cliché Flexo')], max_length=10)),
                ('serial_number', models.CharField(max_length=100, verbose_name='N° Série')),
                ('max_impressions', models.IntegerField(default=1000000, verbose_name='Durée de vie (tours)')),
                ('current_impressions', models.IntegerField(default=0, verbose_name='Tours actuels')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technicalproduct')),
            ],
        ),
    ]
