# Generated by Django 5.2.10 on 2026-01-18 15:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_technicalproduct_num_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, verbose_name='Référence')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant Total')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('SIGNED', 'Signé')], default='DRAFT', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='quotes/', verbose_name='PDF Signé')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
    ]
