# Generated by Django 5.2.10 on 2026-01-25 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsommationEncre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date De Prod')),
                ('process_type', models.CharField(choices=[('FLEXO', 'Flexo'), ('HELIO', 'Hélio')], default='FLEXO', max_length=10, verbose_name='Type Process')),
                ('support', models.CharField(max_length=100, verbose_name='Support')),
                ('laize', models.FloatField(default=0, verbose_name='Laize (mm)')),
                ('bobine_in', models.FloatField(default=0, verbose_name='Total Bobine In (kg)')),
                ('bobine_out', models.FloatField(default=0, verbose_name='Total Bobine Out (kg)')),
                ('metrage', models.FloatField(default=0, verbose_name='Métrage (m)')),
                ('encre_noir', models.FloatField(default=0, verbose_name='Noir')),
                ('encre_magenta', models.FloatField(default=0, verbose_name='Magenta')),
                ('encre_jaune', models.FloatField(default=0, verbose_name='Jaune')),
                ('encre_cyan', models.FloatField(default=0, verbose_name='Cyan')),
                ('encre_dore', models.FloatField(default=0, verbose_name='Doré')),
                ('encre_silver', models.FloatField(default=0, verbose_name='Silver')),
                ('encre_orange', models.FloatField(default=0, verbose_name='Orange')),
                ('encre_blanc', models.FloatField(default=0, verbose_name='Blanc')),
                ('encre_vernis', models.FloatField(default=0, verbose_name='Vernis Anti')),
                ('solvant_metoxyn', models.FloatField(default=0, verbose_name='Metoxyn')),
                ('solvant_2080', models.FloatField(default=0, verbose_name='20/80')),
            ],
            options={
                'verbose_name': 'Conso. Encre & Solvant',
                'verbose_name_plural': 'Conso. Encres & Solvants',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='clientcontact',
            options={'verbose_name': 'Contact Client', 'verbose_name_plural': 'Contacts Clients'},
        ),
        migrations.AlterModelOptions(
            name='incidentlog',
            options={'verbose_name': "Journal d'incident", 'verbose_name_plural': "Journaux d'incidents"},
        ),
        migrations.AlterModelOptions(
            name='interactionlog',
            options={'verbose_name': "Journal d'interaction", 'verbose_name_plural': "Journaux d'interaction"},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Machine', 'verbose_name_plural': 'Machines'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'verbose_name': 'Planning Maintenance', 'verbose_name_plural': 'Plannings Maintenance'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Matière première', 'verbose_name_plural': 'Matières premières'},
        ),
        migrations.AlterModelOptions(
            name='productionorder',
            options={'verbose_name': 'Ordre de fabrication', 'verbose_name_plural': 'Ordres de fabrication'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'Bon de commande', 'verbose_name_plural': 'Bons de commande'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Devis', 'verbose_name_plural': 'Devis'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Fournisseur', 'verbose_name_plural': 'Fournisseurs'},
        ),
        migrations.AlterModelOptions(
            name='technicalproduct',
            options={'verbose_name': 'Produit technique', 'verbose_name_plural': 'Produits techniques'},
        ),
        migrations.AlterModelOptions(
            name='tooling',
            options={'verbose_name': 'Outillage cliché, cylindre', 'verbose_name_plural': 'Outillages cliché, cylindre'},
        ),
        migrations.AlterField(
            model_name='technicalproduct',
            name='cut_length_mm',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Pas de coupe (mm)'),
        ),
        migrations.AlterField(
            model_name='technicalproduct',
            name='num_colors',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nb Couleurs'),
        ),
        migrations.AlterField(
            model_name='technicalproduct',
            name='structure_type',
            field=models.CharField(choices=[('MONO', 'Mono'), ('DUPLEX', 'Duplex'), ('TRIPLEX', 'Triplex')], default='MONO', max_length=20),
        ),
        migrations.AlterField(
            model_name='technicalproduct',
            name='width_mm',
            field=models.FloatField(default=0, verbose_name='Laize (mm)'),
        ),
    ]
