# Generated by Django 5.2.10 on 2026-01-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_consommationencre_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommationencre',
            name='job_name',
            field=models.CharField(default='Sans Nom', max_length=200, verbose_name='Nom du Job'),
        ),
    ]
